### ISSUE TITLE
Smart link is much slower than the Unity version

### ISSUE THREAD

**Issue by samizzo** [Whinarn/MeshDecimator#11]
Hi,

With the same model, this version of the mesh decimator seems much slower than the Unity version.

I haven't profiled it yet but I was just scanning the code and in the Unity version, in the smart link code, when looping over the `borderIndexCount` I notice you generate a vertex hash and then break out of the inner loop. You aren't doing that in this non-Unity version though.

I have a model with several meshes and 64k triangles in each mesh and this double loop over the `borderIndexCount` seems very slow; it takes maybe 5 mins to simplify the model.

I'll try to do some tests and actual profiling, but it was definitely in that inner loop every time I broke into the debugger.

Cheers,
Sam

**Comment by Whinarn** [comment]
Hi @samizzo !

This is correct. A few weeks ago I made a new release of [UnityMeshSimplifier](https://github.com/Whinarn/UnityMeshSimplifier) with huge optimizations (with some instances having up to 15 times faster decimation). And I worked on getting the same optimizations here to [MeshDecimator](https://github.com/Whinarn/MeshDecimator) but was having problems with some tests I made just before the release of it.

Then I haven't had time to deal with it yet. But if you are interested the optimizations are available in the [development branch](https://github.com/Whinarn/MeshDecimator/tree/development). The changes can be seen here: https://github.com/Whinarn/MeshDecimator/compare/master...development

Once I have some available time I will look into the problems I noticed and deal with them in order to make a release.

The problems I noticed were different results of the decimation before the optimizations had been applied to after, so I must have made a mistake somewhere, because the intention was never to adjust the algorithm. So that you know. But if you are not noticing any issues on your side, you are free to use the code available in the [development branch](https://github.com/Whinarn/MeshDecimator/tree/development) until I make a proper release. Be aware that it hasn't been properly tested yet though.

I hope this helps you. Thanks!

**Comment by samizzo** [comment]
Ahh ok! That makes sense! Thanks for the info. I'll close this issue then.
