### ISSUE TITLE
Decimated meshes don't work with prefabs

### ISSUE THREAD

**Issue by ghost** [Whinarn/MeshDecimator#14]
Hello, 

I'm trying to use this with a game I'm working on in Unity. I'm currently facing a problem where after decimating the mesh of an object and then saving it as a prefab, instantiating the prefab forces me to regenerate the meshes otherwise only the original mesh is shown. Is there some work around for this?

Thank you,
Mimi

**Comment by Whinarn** [comment]
Do you save the generated meshes as assets in your Unity project?

I don't think the included example scripts takes care of that (it's been a long time since I last touched this project).

**Comment by Whinarn** [comment]
Sorry, I closed the issue by accident.

I will see if I get time to test it out in the scenario that you are describing. But it shouldn't be too much work to resolve.

**Comment by ghost** [comment]
I'm looking into that now, but Unity doesn't seem to want to let me save the generated meshes. 
Edit: wow, nvm. I found an FBX export utility.

**Comment by Whinarn** [comment]
I tested this now, and it was as I suspected. The generated meshes only live in the scene, and as soon as you create a prefab out of it, the meshes are no longer referenced.

The example scripts that I provided in the Unity Example project doesn't handle this properly. Once the meshes are decimated, the decimated meshes must be serialized as assets in your project, so that they can be referenced by prefabs. These example scripts were only meant to guide the usage of the API and show how they can be used. They were never prepared to be used in real scenarios like this one with prefabs.

If you are using Unity, I strongly suggest to use my other repository instead: https://github.com/Whinarn/UnityMeshSimplifier
It's more clean and should integrate better with Unity. It doesn't include any example scripts (except from some code snippets mentioned in the [README](https://github.com/Whinarn/UnityMeshSimplifier#how-do-i-use-this)).

I'm not actively working on any of these projects, and don't have much time to spare for them. But perhaps I should spend some time to improve the UnityMeshSimplifier and include some better examples that work better right out of the box.

Please let me know if this helps you, and if there's anything else that I can do for you. I would like to close this issue now if you don't mind, since I have no interest in implementing this into the Unity Example in this project. I might even remove the Unity example in this project and redirect people to use [UnityMeshSimplifier](https://github.com/Whinarn/UnityMeshSimplifier) instead.

If you are a programmer, and you would like to fix this yourself, then you want to look at this method in the Unity API: [AssetDatabase.CreateAsset](https://docs.unity3d.com/ScriptReference/AssetDatabase.CreateAsset.html)

Cheers!

**Comment by ghost** [comment]
Sorry for the late response. Using an FBX exporter worked, but I will look at using AssetDatabase to fix this. Thank you!

**Comment by amirebrahimi** [comment]
@mimigsuar - if you're going to use https://github.com/Whinarn/UnityMeshSimplifier, then you might take a look at https://github.com/Unity-Technologies/AutoLOD, too as we have that as the default simplifier and already have support for creating LODs of prefabs or scene objects (you should be able to right click on them and generate a LOD)

**Comment by Whinarn** [comment]
@mimigsuar I just released [v2.0.0](https://github.com/Whinarn/UnityMeshSimplifier/blob/master/CHANGELOG.md) of [UnityMeshSimplifier](https://github.com/Whinarn/UnityMeshSimplifier) which has support for LOD generation based on the example scripts provided in the Unity Example of this project. I made sure to resolve the issue that you experienced here. In case that would be of interest.

It's still very basic however. So for anything more advanced, [AutoLOD](https://github.com/Unity-Technologies/AutoLOD) would have more features.

**Comment by ghost** [comment]
Oh cool! I'll be sure to try it out sometime soon! Thank you so much for all your work.
