### ISSUE TITLE
Decimate leaves holes and artifacts in smooth terrain

### ISSUE THREAD

**Issue by maxilevi** [Whinarn/MeshDecimator#16]
Hi,
First thanks for making this library. Currently I am trying to use it for simplifying my procedurally generated terrain meshes however, running the algorithm through the mesh creates very noticeable holes in the terrain which makes it a deal breaker for me and the lower the threshold the bigger the holes.

Below I attached a pair of pictures, do you have any idea of what may be causing this? I made sure the input mesh is smooth (there are no duplicate vertices) and all the Preserve* properties are enabled, as well as smart link.

Before:
![09-09-2019_02-28-04](https://user-images.githubusercontent.com/8160966/64505301-c650c980-d2a9-11e9-84b5-3cc3d97e4d5b.png)

After:
![09-09-2019_02-28-40](https://user-images.githubusercontent.com/8160966/64505461-52fb8780-d2aa-11e9-83ab-4bf81f86bfc6.png)

Thanks

**Comment by Whinarn** [comment]
That is weird indeed. If it looks like this even after having all preservation options enabled, there must be a bug somewhere. But I haven't seen anything like this before, where it just seems to have removed one triangle.

The only reason that I can think of that would cause this, would be if the triangles weren't connected. But with PreserveBorders enabled, it would prevent pretty much anything from being decimated.

Do you mind exporting your procedurally generated terrain to OBJ or FBX or something and attach it here, so that I can have a closer look?

**Comment by Whinarn** [comment]
Closing this issue because the project is being archived. Consider using [UnityMeshSimplifier](https://github.com/Whinarn/UnityMeshSimplifier) instead, if you are using Unity.
